### ISSUE TITLE
Debug version of runtime library

### ISSUE THREAD

**Issue by lkosson** [hejmus/win10verhack#1]
Hello,

your release has been built using Debug configuration with DLL-based runtime library, resulting in `win10verhack64.dll` requiring `VCRUNTIME140D.dll` to work, which most likely will be missing on non-developers PCs. Please consider switching to statically-linked runtime library (/MT switch instead of /MD) and/or publishing using a Release profile.

**Comment by hejmus** [comment]
true, pushed new release
